services:
  mysql:
    image: mysql:8.4
    container_name: parking-mysql
    environment:
      MYSQL_DATABASE: parking_manager
      MYSQL_USER: parking
      MYSQL_PASSWORD: parking
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  simulator:
    image: cfontes0estapar/garage-sim:1.0.0
    container_name: garage-simulator
    ports:
      - "3000:3000"
      - "3003:3003"

  app:
    build: .
    container_name: parking-api
    network_mode: "service:simulator"
    depends_on:
      mysql:
        condition: service_healthy
      simulator:
        condition: service_started
    environment:
      SERVER_PORT: 3003
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/parking_manager?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: parking
      SPRING_DATASOURCE_PASSWORD: parking
      GARAGE_SIMULATOR_URL: http://localhost:3000

volumes:
  mysql-data:
